version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: event-postgres
    environment:
      POSTGRES_DB: local_events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: event-backend
    container_name: event-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/local_events
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    image: event-frontend
    container_name: event-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: